defaults:
  - _self_

num_envs: 1
freq: 40 # can only be divisible by 200
camera_follow: False
env_name: warehouse
# env_name: full-warehouse

sensor:
  enable_lidar: False
  enable_camera: False
  color_image: False
  depth_image: False
  semantic_segmentation: False

sim_app:
  anti_aliasing: 0
  width: 1280
  height: 720
  hide_ui: True
